# 초난감 예외 처리

> JdbcTemplate 적용 이전에는 있었던 throws SQLException 선언이
적용 후에는 사라졌다. 어디로 갈걸까?

case 1. 예외 블랙홀
---

```java
발생한 예외를 먹어버렸다.
try {
    ...
}catch(SQLException e){ // 예외를 잡고 아무것도 하지 않는다.
}
```

case 2. 화면에 메시지 출력하기 != 예외 처리
---

```java
예외를 처리하지 않고, 메시지만 출력하고 있다.
try {
    ...
}catch(SQLException e){
    System.out.println(e);  //
}
// 또는
try {
    ...
}catch(SQLException e){
    e.printStackTrace(); //
}
// 모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키든지 처리를 해야한다.
// 메시지를 출력한다고 예외를 처리한 것이 아니다.
```

---
###즉, 예외를 무시하거나 잡아먹는 코드를 만들지말자
```java
예외를 무시하고 정상적으로 동작하고 있는 것처럼 모른척하는 것보다는 낫다.
try {
    ...
}catch(SQLException e){
    e.printStackTrace();
    System.exit(1);
}

// 뭔가 조치를 취할 방법이 없다면 굳이 예외를 잡지 말아야 한다.
// 대신 던져버릴 것.
// ( 메서드에 throws SQLException을 선언해서 메서드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가해라)
```
---
case 3. 무의미하고 무책임한 throws
---
> EJB가 한창 쓰이던 시절에 흔히 볼 수 있던 코드다.

```java
throws Exception을 기계적으로 붙여놨다.

public void method1() throws Exception {
    method2();
}

public void method2() throws Exception {
    method3();
}

public void method3() throws Exception {
    method4();
}
// 이 경우 메서드 선언에서 의미있는 정보를 얻을 수 없다. 다 Exception이니까.
// 심지어 이게 진짜 Exception이 생길거 같아서 붙인건지 그냥 기계적으로 복붙한건지도 알수 없음.
// 예외를 처리할 수 있는 기회를 박탈한다.
```
---
<p align="center">
<img width="90" src="../images/icons/dinosaur.png"><br>
</p>

> 그렇다면 예외를 어떻게 다뤄야할까?

### 예외의 종류와 특징
```java
자바 개발자들 사이에서 예외처리에 관해서 가장 큰 이슈로 다뤄지는 것이 '체크예외'다.

체크예외 checked Exception
: 명시적인 처리가 필요한 예외를 사용하고 다루는 방법
```
####자바에서 throws를 통해 발생시킬 수 있는 예외 3가지
- **Error**
  > java.lang.Error클래스의 서브클래스들

  - 시스템에 뭔가 비정상적인 상황이 발생했을 경우
  - 주로 자바 VM에서 발생시키는 에러다.
  - 따라서, 애플리케이션 코드에서 잡으려고 하면 안된다. catch블록으로 잡아봤자 대응방법이 없음..
  - ex. OutOfMemoryError, ThreadDeath
- **Exception과 체크예외**
  > java.lang.Exception 클래스와 그 서브클래스로 정의되는 예외들

  - 개발자들이 만든 애플리케이션 코드의 작업 중에 **예외상황이 발생했을 경우** 사용된다.
  - 체크예외와 언체크예외unchecked exception으로 구분된다.
  - **체크예외**
    - Exception클래스의 서브클래스
    - RuntimeException클래스를 상속하지 않은 것들
  - **언체크예외**   ▶ 자바는 이 예외를 특별하게 다룬다.
    - Exception클래스의 서브클래스
    - RuntimeException클래스를 상속한 클래스들
  - 일반적으로 예외라고 하면 체크예외를 말한다고 생각해도 된다.
  - `체크예외가 발생할 수 있는 메서드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야한다.`
    > 사용할 메서드가 체크 예외를 던진다면
    > 이를 catch문으로 잡든지, 아니면 throws를 정의해서 메서드 밖으로 던지든지 처리해야함.
    > 그렇지 않으면 컴파일에러 발생함.
  - IOException이나 SQLException을 비롯한 예외적인 상황에서 던져질 가능성이 잇는 것들 대부분이 체크예외로 만들어져 있다.
    > 체크 예외를 발생가능한 예외에 모두 적용하려했던 초기설계자들의 의도가 보임!
    > 하지만 이 때문에 비난을 많이 받았음..
    > 체크 예외가 예외처리를 강제하는 것 때문에 예외블랙홀이나 무책임한 throws 코드가 남발됐기 때문
    > 따라서 최근에 새로 등장하는 자바 표준 스펙 API들은 예상 가능한 예외상황을 다루는 예외를 체크 예외로 만들지 않는 경향이 있음.
- **RuntimeException과 언체크/런타임 예외**
  > java.lang.RuntimeException 클래스를 상속한 예외들

  - 명시적인 예외처리를 강제하지 않기 때문에 언체크 예외라 불린다.
  - 대표 클래스(RuntimeException)의 이름을 따서 런타임예외라고도 불린다.
  - 에러와 마찬가지로 catch문으로 잡거나 throws로 선언하지 않아도된다.
    > 물론 해줘도 상관 없긴함.
  - 주로 프로그램의 오류가 있을 때 발생하도록 의도된 예외들이다.
  - 대표적인 예
    - NullPointerException : 오브젝트를 할당하지 않은 레퍼런스 변수를 사용하려고 시도했을때 발생
    - IllegalArgumentException : 허용되지 않는 값을 사용해서 메서드를 호출할 때 발생
  - 코드에서 미리 조건을 체크하도록 주의 깊게 만든다면 피할 수 있는 예외들이다.
  - 피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 만든 예외
  - `런타임예외는 예상하지 못했던 예외 상황에 발생하는 것이 아니므로 굳이 catch나 throws를 사용하지 않아도 되도록 만든 것이다.`

### 예외처리 방법

> 예외를 처리하는 일반적인 방법과 효과적인 전략을 알아보자

1
---
####예외 복구
예외 상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것

```java
예외 상황 : 사용자가 요청한 파일을 읽으려고 시도했는데 해당 파일이 없다거나 다른 문제가 있어서 읽히지 않아서 IOException이 발생했다.

해결 방법 : 사용자에게 상황을 알려주고 다른 파일을 이용하도록 안내한다.
// 예외로 인해 기본 작업 흐름이 불가능하면 다른 작업 흐름으로 자연스럽게 유도해준다.

예외가 복구되었다!

단!
여기서 IOException 에러메시지가 사용자에게 그냥 던져지는 것은 예외 복구라 할 수 없다.
// 예외가 처리됐으면 애플리케이션은 정상적으로 설계된 흐름을 따라 진행돼야 한다.
// 에러메시지가 던져진게 에러가 처리되었다는게 아니라는 것 주의!
```

```java
예외 상황 : 네트워크가 불안해서 가끔 서버에 접속이 잘 안되는 열악한 환경에 있는 시스템이다. 원격 DB 서버에 접속하다 실패해서 SQLException이 발생했다.

해결 방법 : 재시도 한다. 일정시간 대기했다가 다시 접속을 시도해보는 방법을 사용한다.
// 물론 정해진 횟수만큼 재시도해서 실패했다면 예외복구는 포기해야 한다.

통제 불가능한 외부 요인으로 인해 예외가 발생하면 MAX_RETRY만큼 재시도를 한다.
// 사전에 미리 성공 여부를 확인할 수 없고, 재시도가 의미있는 경우라면 이렇게 최대 횟수만큼 반복적으로 시도함으로써 예외상황에서 복구되게 할 수 있다.
```
- 예외처리 코드를 강제하는 체크예외들은 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다.
- API를 사용하는 개발자로 하여금 예외 상황이 발생할 수 있음을 인식하도록 도와주며 이에 대한 적절한 처리를 시도해보도록 요구하는 것이다.

**[예외복구 예시] 재시도를 통해 예외를 복구하는 코드**
```java
int maxretry = MAX_RETRY;
while(maxretry -- > 0 ){
    try{
        ...     // 예외가 발생할 가능성이 있는 시도
        return; // 작업 성공
    }
    catch(SomeException e){
        // 로그 출력. 정해진 시간만큼 대기
    }
    finally {
        // 리소스 반납. 정리 작업
    }
}
throw new RetryFailedException();  // 최대 재시도 횟수를 넘기면 직접 예외 발생
```

2
---
#### 예외처리 회피
예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것
- throws문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 (회피 #1)
- catch문으로 일단 예외를 잡은 후에 로그를 남기고 **다시 예외를 던지는(retrhow)** 것(회피 #2)

> 예외를 빈 catch블록으로 잡아서 예외가 발생하지 않은 것처럼 만드는 경우는
>   1. 특별한 의도가 있을 경우(드물다..)
>   2. 아무 개념이 없을 경우(...)
>
> 아무쪼록 이건 회피가 아님..!
> 예외를 회피하려면 **반드시** 다른 오브젝트나 메서드가 대신 처리하도록 던져줘야한다.

```java
회피 #1
public void add() throws SQLException {
    // JDBC API
}
```
```java
회피 #2
public void add() throws SQLException {
    try{
        // JDBC API
    }
    catch(SQLException e){
        // 로그 출력
        throw e;
    }
}
```
JdbcContext나 JdbcTemplate이 사용하는 콜백 오브젝트
=> ResultSet, PreparedStatement를 이용한 작업중에 발생하는 SQLException을 자신이 처리하지 않고 템플릿으로 던져버린다. SQLException을 처리하는 일은 콜백 오브젝트의 역할이 아니라고 보기 때문!
> 따라서 콜백 오브젝트의 메서드는 모두 throws SQLException이 붙어있다. (회피)
> 템플릿 레벨에서 처리하도록 던져준다.

#####하지만
콜백과 템플릿처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는 건 무책임한 책임회피일 수 있다.
> 예를 들어 DAO, 서비스 계층, 웹 컨트롤러가 있다고 하자.
> (서로 긴밀하게 역할을 분담하는 사이가 아님!)
> DAO에서 SQLException 생각없이 던짐 -> 서비스 계층도 다시 던짐 -> 컴트롤러도 다시 던짐 -> 결국 서버로 전달됨..

예외를 회피하는 것 역시 예외를 복구하는 것처럼 의도가 분명해야한다.
- 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명히 지게 한다.(콜백/템플릿처럼)
- 자신을 사용하는 쪽에서 예외를 다루게 한다.

어느 방법이 되었든 그것이 최선의 방법이라는 분명한 확신이 있어야한다.

3
---
####예외 전환
> exception translation

예외 회피와 비슷하게 예외를 복구해서 정상적인 상태로는 만들 수 없기 때문에 예외를 메서드 밖으로 던진다. 하지만 예외 회피와 달리, 발생한 예외를 **그대로 넘기는게 아니라 적절한 예외로 전환** 해서 던진다.

예외 전환의 목적
- 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우 **의미를 분명하게 해줄 수 있는 예외로 바꿔주기 위해서**
  - 예 : API가 발생하는 기술적인 로우레벨을 상황에 적합한 의미를 가진 예외로 변경하는 것
    ```java
    예외 상황 : 새로운 사용자를 등록하려고 시도했을 때 아이디가 같은 사용자가 있어서 DB에러가 발생했다.
               이 경우 JDBC API는 SQLException을 발생시킨다.

    해결 방법 1 : DAO메서드에서 SQLException을 밖으로 던진다.
                => (DAO를 이용해 사용자를 추가하려 한)서비스 계층에서는
                왜 SQLException이 발생했는지 쉽게 알 방법이 없읍.
                물론 서비스 계층 오브젝트에서 SQLException의 원인을 해석해서 대응하는 것도 불가능은 아님.
                그러나 특정 기술의 정보를 해석하는 코드를 비즈니스 로직을 담은 서비스 계층에 두는 것은 매우 어색함..

    해결 방법 2 : 로그인 아이디 중복 같은 경우는 충분히 예상 가능하고 복구가능한 예외상황이다.
                그러므로 DAO에서 SQLException의 정보를 해석해서 DuplicateUserIdException 같은 예외로 바꿔서 던져준다.
                => 의미가 분명한 예외가 던져졌으므로 서비스 계층 오브젝트에서는 적절한 복구 작업을 시도할 수 있다.

    방법2와 같이 DAO메서드에서 기술에 독립적이며 의미가 분명한 예외로 전환해서 던져줄 필요가 있다.
    ```
    ```java
    예외전환 기능(방법 2)을 가진 DAO메서드
    public void add(User user) throws DuplicateUserIdException, SQLException {
        try{
            // JDBC를 이용해 user정보를 DB에 추가하는 코드
            // 혹은 그런 기능을 가진 다른 SQLException을 던지는 메서드를 호출하는 코드
        }
        catch(SQLException e){
            // ErrorCode가 MYSQL의 "Duplicate Entry(1062)"이면 예외 전환
            if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
                throw DuplicateUserIdException();
            else
                throw e;  // 그 외의 경우는 SQLException 그대로
        }
    }
    ```
  - 팁 : 보통 전환하는 예외에 원래 발생한 예외를 담아서 **중첩 예외(nested exception)** 로 만드는 것이 좋다.
    - 중첩 예외는 getCause()메서드를 이용해서 처음 발생한 예외가 무엇인지 확인할 수 있다. 그러려면 처음 발생한 예외를 넘겨줘야하는데
      1. 새로운 예외를 만들면서 생성자에 넣어준다.
      ```java
      catch(SQLException e){
          ...
          throw DuplicateUserIdException(e);
      }
      ```
      2. initCause()메서드를 이용해 넣어준다.
      ```java
      catch(SQLException e){
          ...
          throw DuplicateUserIdException().initCause();
      }
      ```
- 예외를 처리하기 쉽고 단순하게 만들기 위해 포장wrap한다.
의미를 명확히 하기 위함이 아니라 예외처리를 강제하는 **체크 예외를 언체크 예외인 런타임 예외로 바꾸기 위해서**
    - 중첩 예외를 이용해 새로운 예외를 만들고 원인cause이 되는 예외를 내부에 담아서 던지는 방식은 같다.
    - 예1 : EJBException.
    EJB 컴포넌트 코드에서 발생하는 대부분의 체크 예외는 비즈니스 로직으로 볼 때 의미있는 예외이거나 복구가능한 예외가 아니다.
    `이런 경우 런타임 예외인 EJBException으로 포장해서 던지는 편이 낫다.`
      ```java
      예외 포장
      try {
          OrderHome orderHome = EJBHomeFactory.getInstance().getOrderHome();
          Order order = orderHome.findByPrimaryKey(Integer id);
      } catch (NamingException ne){
          throw new EJBException(ne);
      } catch (SQLException se){
          throw new EJBException(se);
      } catch (RemoteException re){
          throw new EJBException(re);
      }
      ```
      > EJBException은 RuntimeException클래스를 상속한 런타임 예외다.

    - 런타임 예외로 만들어서 전달하면 EJB는 이를 시스템 exception으로 인식하고 트랜잭션을 자동으로 롤백해준다.
      > 런타임 예외이기 때문에 EJB컴포넌트를 사용하는 다른 EJB나 클라이언트에서 일일이 예외를 잡거나
      > 다시 던지는 수고를 할 필요가 없다.
      ```
      일반적으로 체크 예외를 계속 throws를 사용해 넘기는 건 무의미하다.

      - 메서드 선언 지저분해짐..
      - DAO에서 발생한 SQLException이 웹 컨트롤러 메서드에까지 명시적으로 전달된다고 해서 무슨 소용인가?
      - 누군가가 웹 컨트롤러 메서드만 딱 봤는데 거기에 throws SQLException 선언이 달려있으면 이를 어떻게 해석해야할까?
      - 어차피 복구가 불가능한 예외라면 가능한 한 빨리 런타임 예외로 포장해 던지게 해서
        다른 계층의 메서드를 작성할 때 불필요한 throws 선언이 들어가지 않도록 하자.
      ```

    - 예2 : 예1과 반대로 애플리케이션 로직상에서 예외조건이 발견되거나 예외 상황이 발생할 수도 있는데 이런 것은 API가 던지는 예외가 아니라 애플리케이션 코드에서 의도적으로 던지는 예외다.
    `이 때는 체크예외를 사용하자.`
    `비즈니스적인 의미가 있는 예외는 이에 대한 적절한 대응이나 복구 작업이 필요하기 때문이다.`

### 예외처리 전략

> 예외를 **효과적으로** 사용하고, 예외가 발생하는 코드를 깔끔하게 정리하는게 중요함!
> 일관된 예외처리 전략을 세우자!

1
---
####런타임 예외의 보편화
---
- 체크예외
  - 일반적인 예외를 다룬다.
  - 복구할 가능성이 조금이라도 있는 예외적인 상황이므로
    이를 처리하는 catch블록이나 throws선언을 강제한다.
    > 이렇게 예외처리를 강제하는 것은
      예외가 발생할 가능성이 있는 API메서드를 사용하는 개발자의 실수를 방지하기 위한 배려다..?
      => 실제로는 예외를 다루고 싶지 않게 만드는 원인 중 하나임..

- 언체크예외
  - 시스템 장애나 프로그램상의 오류에 사용한다.
---

- 독립형 애플리케이션
  - 자바가 처음 만들어질 때 많이 사용되던 애플릿이나 AWT, Swing을 사용한 독립형 애플리케이션
  - 통제 불가능한 시스템 예외라 할지라도 애플리케이션 작업이 중단되지 않게 해주고 상황을 복구해야했다.

- 자바 엔터프라이즈 서버환경
  - 수많은 사용자가 동시에 요청을 보내고 각 요청이 독립적인 작업으로 취급된다.
  - 하나의 요청을 처리하는 중에 예외가 발생하면 해당 작업만 중단시킨다.
    > 독립형 애플리케이션처럼 작업을 일시 중지시키고 예외상황을 복구할 방법 없음.

  - 차라리 애플리케이션 차원에서 예외상황을 **미리** 파악하고,
  예외가 발생하지 않도록 차단하는게 좋다.
  - 프로그램의 오류나 외부환경으로 인해 예외가 발생하는 경우라면
  빨리 해당 요청의 작업을 취소하고 서버관리자나 개발자에게 통보한다.
---
즉,
`자바의 환경이 서버로 이동하면서 체크 예외의 활용도와 가치는 점점 떨어지고 있다.`
`대응이 불가능한 체크예외라면 빨리 런타임 예외로 전환해서 던지는 게 낫다.`


- 자바 초기와 달리 최근에는
 API가 발생시키는 예외를 체크 예외 대신 언체크 예외로 정의하는 것이 일반화 되고 있다.

- 일단 언체크 예외로 만드는 경향이 있다.
  언체크 예외라도 필요하면 얼마든지 catch블록으로 잡아서 복구하거나 처리할 수 있으므로..

#### add() 메서드의 예외처리
```java
public void add(User user) throws DuplicateUserIdException, SQLException
```
- 두 가지의 체크 예외를 던지고 있다.
  - SQLException
      - 원인이 ID 중복이면
        좀 더 의미있는 예외인 DuplicateUserIdException 예외로 전환해서 던진다.
      - 그 외에는 그대로 던진다.
      - **하지만 그보다 SQLException은 대부분 복구 불가능한 예외이므로 잡으나마나임.**
      - 결국 throws를 타고 계속 앞으로 전달되다가 애플리케이션 밖으로 던져질 것이다.
      - 그럴 바에는 그냥 런타임 예외로 포장해서 던지자. ( 다른 메서드들이 신경쓰지 않아도 되도록 )
  - DuplicateUserIdException
      - 충분히 복구 가능한 예외다.
      - add() 메서드를 호출한(사용하는) 쪽에서 잡아서 대응할 수 있다.
      - 또는 더 앞단의 오브젝트에서 다룰 수도 있다.
      - 어디에서든 잡아서 처리할 수 있는 예외이므로
      굳이 체크예외로 만들지 말고 런타임 예외로 만들자.
      - add() 메서드에 명시적으로 DuplicateUserIdException를 던진다고 선언해야한다.
        > 런타임 예외도 throws로 선언할 수 있으니 걱정하지 말 것!

      - 그래야 add()메서드를 사용하는 코드를 만드는 개발자에게 의미 있는 정보를 전달해줄 수 있다.

**DuplicateUserIdException**
```java
사용자 아이디가 중복됐을 때 사용하는 DuplicateUserIdException을 만들자.

public class DuplicateUserIdException extends RuntimeException {

    // 중첩 예외를 만들 수 있도록 생성자를 추가했다!
    public DuplicateUserIdException(Throwable cause){
        // 메시지나 예외상황을 전달하는 데 필요한 정보를 더 넣을 수도 있다.
        super(cause);
    }
}
```
- 필요하면 언제든 잡아서 처리할 수 있도록 별도의 예외로 정의하기는 하지만, 필요 없다면 신경 쓰지 않아도 되도록 RuntimeException을 상속한 런타임 예외로 만든다..... ??

**add() 메서드 수정**
```java
public void add(User user) throws DuplicateUserIdException, SQLException {
    try{
        // JDBC를 이용해 user정보를 DB에 추가하는 코드
        // 혹은 그런 기능을 가진 다른 SQLException을 던지는 메서드를 호출하는 코드
    }
    catch(SQLException e){
        // ErrorCode가 MYSQL의 "Duplicate Entry(1062)"이면 예외 전환
        if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw DuplicateUserIdException();
        else
            throw e;  // 그 외의 경우는 SQLException 그대로
    }
}
```
- SQLException을 직접 메서드 밖으로 던진다.

<p align="center">
<img width="40" src="../images/icons/hand-finger-pointing-down.png"><br>
</p>
```java
public void add(User user) throws DuplicateUserIdException {
    try{
        // JDBC를 이용해 user정보를 DB에 추가하는 코드
        // 혹은 그런 기능이 있는 다른 SQLException을 던지는 메서드를 호출하는 코드
    }
    catch(SQLException e){
        if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
            throw new DuplicateUserIdException(e);   // 예외 전환!!
        else
            throw new RuntimeException(e);  // 예외 포장!!
    }
}
```
- SQLException을 런타임 예외로 전환해서 던진다.
  > 이제 SQLException은 언체크 예외가 됐다.

- DuplicateUserIdException도 언체크 예외로 만들어지긴 했지만
add() 메서드를 사용하는 쪽에서 아이디 중복 예외를 처리하고 싶은 경우
활용할 수 있음을 알려주도록
메서드의 throws선언에 DuplicateUserIdException를 포함시켰다.

- 이 add() 메서드를 사용하는 오브젝트는 SQLException을 처리하기 위해 불필요한 throws 선언 안해도 됨.


이처럼 런타임 예외를 일반화해서 사용하는 방법은 장점이 많으나
주의해야할 것이 있다.
- 컴파일러가 예외처리를 강제하지 않으므로 신경 써서 예외상황을 충분히 고려할 것!!
- 따라서, 런타임 예외를 사용하는 경우에는
  API 문서나 레퍼런스 문서등을 통해 메서드를 사용할 때
  발생할 수 있는 예외의 종류와 원인, 활용 방법을 자세히 설명해두자!

2
---
####애플리케이션 예외
> 시스템 또는 외부의 예외상황이 원인이 아니라 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고,
> 반드시 catch해서 무엇인가 조치를 취하도록 요구하는 예외다.

```java
예를 들면,

사용자가 요청한 금액을 은행계좌에서 출금하는 기능을 가진 메서드가 있다고 해보자.
=> 무턱대고 출금 허용, 현재 잔고가 얼마인지 상관없이 요청한 금액만큼 계좌 잔액을 차감(X)

=> 계좌 잔액을 확인, 허용하는 범위를 넘어서 출금을 요청하면 출금작업을 중단시킨다.
    사용자에게 적절한 경고
```
**메서드 설계 방법 두 가지**
- `각각의 경우에 다른 종류의 리턴 값을 돌려준다.`
  > 리턴 값 = 일종의 결과 상태를 나타내는 정보

  - 정상적인 출금처리를 했을 경우 => 요청금액 자체
  - 잔고 부족이 발생했을 경우 => 0 또는 -1 같은 특별한 값
  <br>

  이 메서드를 호출한 쪽은 반드시 리턴 값을 확인하고
  경우에 따라 작업흐름을 달라지게 한다.

  ```
  단점 1 : 예외 상황에 대한 리턴 값을 명확하게 코드화하고 잘 관리하지 않으면 혼란이 생길 수 있다.

  즉, 개발자마다 정상적인 처리가 안됐을 때 전달하는 값에 대한 생각이 다르다.
  어떤 이는 0을, 또 다른이는 -1이나 -999돌려주기도 한다.

  따라서, 일관된 예외상황에서의 결과값에 대한 정책을 완벽하게 갖춰야한다.
  또한 사전에 상수로 정의해둔 표준코드가 있다고 해도 이를 사용하지 않게 되는 경우(실수로.. 또는 몰라서.. ) 개발자 사이의 의사소통 문제로 인해 제대로 동작하지 않을 위험이 있다.

  단점 2 : 결과 값을 확인하는 조건문이 자주 등장한다
  if 블록이 범벅된 코드가 됨..! 지저분해지고 흐름 파악이 어려워짐.
  ```
- `잔고 부족과 같은 예외상황에 비즈니스적인 의미를 띈 예외를 던지도록 한다.`
  >정상적인 흐름을 따르는 코드는 그대로 두고..!

  - 잔고 부족인 경우 InsufficientBalanceException을 던진다.
    - 이 예외는 명시적으로 체크 예외로 만든다.
    - 개발자가 잊지 않고 잔고부족처럼 자주 발생 가능한 예외상황에 대한 로직을 구현하도록 강제하기 위해서!
    - 기본적으로 런타임예외로 만들어두는 것보다 상대적으로 안전하다
    - 애플리케이션 예외 이므로 예외상황에 대한 상세한 정보를 담고 있도록 설계하자!
      ex. 잔고가 부족한 경우라면 현재 인출 가능한 최대 금액은 얼마인지 확인해서 예외 정보에 넣어준다.
  - 정상적인 흐름을 따르지만 예외가 발생할 수 있는 코드르 try블록 안에 깔끔하게 정리해둔다.
  - 예외 상황에 대한 처리는 catch블록에 모아둔다.
  ```java
  try{
      BigDecimal balance = account.withdraw(amount);
      ...
      // 정상적인 처리 결과를 출력하도록 진행
  }
  catch(InsufficientBalanceException e){
      // InsufficientBalanceException이 담긴 인출 가능한 잔고금액 정보를 가져온다.
      BigDecimal availFunds = e.getAvailFunds();
      ...
      // 잔고 부족 안내 메시지를 준비하고 이를 출력하도록 진행
  }
  ```

---
- 런타임 예외 중심의 전략
  **= 낙관적인 예외 처리 기법**
<br>
- 체크 예외 중심의 전략
  **= 비관적인 예외 처리 기법**
  - 직접 처리할 수 없는 예외가 대부분이라 하더라도
  혹시 놓칠 경우를 대비해 일단 잡고 보도록 강제한다.
---

###그래서 JdbcTemplate 적용하는 중에 throws SQLException선언이 왜 사라졌는가?!
- SQLException은 99% 복구 불가능한 예외다.
  > 프로그램 오류, 개발자의 부주의(SQL문법 틀렸거나, 제약조건 위반했거나), 통제할 수 없는 외부상황(네트워크 불안정, DB서버 다운, DB 커넥션 풀이 꽉 차서 DB커넥션 가져올 수 없는 경우) 에 의한 예외이므로..

따라서 예외처리 전략을 적용해야한다.
가능한 한 빨리 언체크/런타임 에외로 전환해줘야한다.

스프링의 JdbcTemplate은 바로 이 예외처리 전략을 따르고 있다.
JdbcTemplate 템플릿과 콜백 안에서 발생하는 모든 SQLException을 런타임 예외인 DataAccessException으로 포장해서 던져준다.
따라서 JdbcTemplate을 사용하는 UserDao 메서드에선 꼭 필요한 경우에만 런타임 예외인 DataAccessException을 잡아서 처리하면 되고 그외의 경우엔 무시해도 됨.

그래서 DAO메서드에 SQLException이 모두 사라진 것!
JdbcTemplate의 update(), queryForInt(), query() 메서드 선언을 보면 모두
throws DataAccessException이라고 되어있다!

throws로 선언되어 있긴 하지만 DataAccessException이 런타임 예외이므로
update()를 사용하는 메서드에서 이를 잡거나 다시 던질 의무는 없다.

```java
public int update(final String sql) throws DataAccessException { ... }
```

스프링의 API 메서드에 정의되어 있는 대부분의 예외는 런타임 예외다.
